### ISSUE TITLE
Set relative dim level command malfunction

### ISSUE THREAD

**Issue by Moskvitch** [jghaanstra/com.yeelight#1] opened 2020-01-21 21:59 UTC
When set to negative value, like “-20%”, turns the bulb off completely instead of dimming.

**Comment by jghaanstra** [comment] 2020-01-23 22:52
I have tested this and this is a bug in Homey core (or perhaps they think it works as intended). Please report this to Athom if you feel the seem way after reading the following. You can also reference these details if you send this to Homey.

"When using negative values with the relative dim card sometimes the value passed on to dim capabilityListener is 0 instead of the relative value from the current dim. This can happen as it's not actually calculated relatively from the actual value but substracted as absolute number.  Dimming by 20% when current dim level is 50% will result in a dim level of 30%. If it would be relative the value would be 40% (50 - (50*0,2)). So dimming by 60% when current dim level is 50% will result in a dim level of 0."

I'm closing this for now as I have no control over this. I have deliberatly coded the app that it will turn of the light when a dim value is 0% is set.

**Closed by jghaanstra** 2020-01-23 22:52 UTC
